name: Stash
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+8

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  google_mlkit_barcode_scanning: ^0.12.0
  glass: ^2.0.0+1
  barcode_widget: ^2.0.4
  shared_preferences: ^2.3.2
  screen_brightness: ^1.0.1
  flutter_svg: ^2.0.10+1
  mesh_gradient: ^1.3.7
  in_app_review: ^2.0.9
  package_info_plus: ^8.0.2
  webview_flutter: ^4.8.0
  cached_network_image: ^3.4.1
  image: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2
  provider: ^6.1.2
  cached_network_svg_image: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  haptic_feedback: ^0.5.1+1
  http: ^1.2.2
  flutter_statusbarcolor_ns: ^0.5.0
  in_app_purchase: ^3.2.0
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
        - asset: fonts/SF-Pro-Display-BlackItalic.otf
        - asset: fonts/SF-Pro-Display-Bold.otf
        - asset: fonts/SF-Pro-Display-BoldItalic.otf
        - asset: fonts/SF-Pro-Display-Heavy.otf
        - asset: fonts/SF-Pro-Display-HeavyItalic.otf
        - asset: fonts/SF-Pro-Display-Light.otf
        - asset: fonts/SF-Pro-Display-LightItalic.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
        - asset: fonts/SF-Pro-Display-MediumItalic.otf
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-RegularItalic.otf
        - asset: fonts/SF-Pro-Display-Semibold.otf
        - asset: fonts/SF-Pro-Display-SemiboldItalic.otf
        - asset: fonts/SF-Pro-Display-Thin.otf
        - asset: fonts/SF-Pro-Display-ThinItalic.otf
        - asset: fonts/SF-Pro-Display-Ultralight.otf
        - asset: fonts/SF-Pro-Display-UltralightItalic.otf
    - family: SFProRounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Black.otf
        - asset: fonts/SF-Pro-Rounded-Bold.otf
        - asset: fonts/SF-Pro-Rounded-Heavy.otf
        - asset: fonts/SF-Pro-Rounded-Light.otf
        - asset: fonts/SF-Pro-Rounded-Medium.otf
        - asset: fonts/SF-Pro-Rounded-Regular.otf
        - asset: fonts/SF-Pro-Rounded-Semibold.otf
        - asset: fonts/SF-Pro-Rounded-Thin.otf
        - asset: fonts/SF-Pro-Rounded-Ultralight.otf
  assets:
    - assets/penny.svg
    - assets/icons/home.svg
    - assets/icons/percent.svg
    - assets/icons/settings.svg
    - assets/icons/stars.svg
    - assets/icons/profile.svg
    - assets/icons/palette.svg
    - assets/icons/hex.svg
    - assets/icons/profileheart.svg
    - assets/logo.png
    - assets/lottie/tickw.json
    - assets/lottie/tick.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
